version: '3.8'
  
services:
  jenkins:
    container_name: jenkins
    image: test-jenkins:latest
    user: "root"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home:
    external: true


# sudo chown jenkins:docker /var/run/docker.sock
# sudo chmod 660 /var/run/docker.sock